### ISSUE TITLE
Add a README for the URDF model description

### ISSUE THREAD

**Issue by claudia-lat** [ami-iit/human-model-generator#14]
In https://github.com/ami-iit/human-model-generator/tree/main/models/humanModelTemplate we'll add a README with a detailed image and a general description of the model elements.

**Comment by LorenzoFiori** [comment]
After the code reorganization (https://github.com/ami-iit/human-model-generator/pull/15) I added a README file with a more detailed presentation of the models [here](https://github.com/ami-iit/human-model-generator/blob/main/code/models/README.md).

Closing the issue
