### ISSUE TITLE
Release first version 

### ISSUE THREAD

**Issue by lrapetti** [ami-iit/human-model-generator#2]
We should release a first version of the software tool able to generate URDF models of subjects starting from anthropometric measurements.

While doing this we should structure the repository such that it can be easily installed and utilized.

TODO:
- [x] Open PR with the Python scripts that generates the model (https://github.com/ami-iit/human-model-generator/pull/1)
- [x] Open PR for readme and documentation (https://github.com/ami-iit/human-model-generator/pull/3)
- [x] Open PR with the Python project structure

**Comment by LorenzoFiori** [comment]
We successfully launched the initial version of the Human Model Generator tool. I close this issue! @lrapetti
