### ISSUE TITLE
Generated model mass different from input mass

### ISSUE THREAD

**Issue by lrapetti** [ami-iit/human-model-generator#5]
I have tried to use the tool by selecting a mass of 79Kg by setting the variable at https://github.com/ami-iit/human-model-generator/blob/main/src/GenerateModel.py#L8. However, checking the model mass using [`idyntree` tool](https://github.com/robotology/idyntree#idyntree-model-info):
```sh
idyntree-model-info -m  HumanModelGeneratehumanModel.urdf --total-mass
```
then the output is the following
```sh
The total mass of model is 89.0258 Kg.
```

**Comment by LorenzoFiori** [comment]
I should have fixed the problem! with this [commit](https://github.com/ami-iit/human-model-generator/commit/2b5d8399e35d53c40ab6eed4ea12adad18cd8e1b). 

@lrapetti can you confirm this?

**Comment by lrapetti** [comment]
> I should have fixed the problem! with this [commit](https://github.com/ami-iit/human-model-generator/commit/2b5d8399e35d53c40ab6eed4ea12adad18cd8e1b).
> 
> @lrapetti can you confirm this?

I tested, there is still 0.01% if error (subject 100Kg, output model 99,99Kg), I think you can fixed it to be more precise adding it to the Pelvis.

**Comment by LorenzoFiori** [comment]
@lrapetti I fixed the last small error on the mass (I added and removed on the pelvis to both models). Now the input mass is also the scaled model mass.

**Comment by lrapetti** [comment]
This issue was solved with https://github.com/ami-iit/human-model-generator/pull/4, we can close it!

Thanks @LorenzoFiori
