### ISSUE TITLE
Reduce the number of DoFs of the URDF model

### ISSUE THREAD

**Issue by AntonellaTatarelli** [ami-iit/human-model-generator#7]
In this issue, we will look at the degrees of freedom of the model created by HMG. 
The model currently has 60 degrees of freedom and is hence overcomplicated.
One approach to reduce this complexity is to consider only the motions that the links can really make in space.

**Comment by claudia-lat** [comment]
@LorenzoFiori what about this activity. If you are not working on this close it and reopen when needed.

**Comment by LorenzoFiori** [comment]
Of course, @claudia-lat . I could temporarily close this issue and reopen it when I am able to work on it.
